# Generated by Django 6.0.2 on 2026-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('STAFF', 'Staff'), ('ADMIN', 'Administrator')], default='GUEST', max_length=20),
        ),
    ]
