# Generated by Django 6.0.2 on 2026-03-16 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.CharField(choices=[('FREE', 'Free (100% refund)'), ('STANDARD', 'Standard (50% refund)'), ('NON_REFUNDABLE', 'Non-Refundable (0% refund)')], default='FREE', help_text='Policy for this booking', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded (if any)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Why the refund was issued', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_transaction_id',
            field=models.CharField(blank=True, help_text='Refund transaction ID from payment provider', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('STRIPE', 'Stripe'), ('PAYMONGO', 'PayMongo (GCash/Cards)'), ('MAYA', 'Maya'), ('GCASH', 'GCash'), ('BANK_TRANSFER', 'Bank Transfer')], default='STRIPE', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=20),
        ),
    ]
