# Generated by Django 4.2 on 2026-04-09 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator')], default='GUEST', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomHousekeepingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('MAINTENANCE', 'Under Maintenance')], max_length=20)),
                ('current_status', models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('MAINTENANCE', 'Under Maintenance')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about room condition or maintenance needs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Related booking if status change is due to booking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_logs', to='authentication.room')),
                ('updated_by', models.ForeignKey(limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Housekeeping Log',
                'verbose_name_plural': 'Room Housekeeping Logs',
                'db_table': 'room_housekeeping_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested by Staff'), ('APPROVED', 'Approved by Manager'), ('REJECTED', 'Rejected by Manager'), ('ISSUED', 'Refund Issued by Admin')], default='REQUESTED', help_text='Current status of refund request', max_length=20)),
                ('reason', models.TextField(help_text='Reason for refund request')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount initially requested for refund', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by manager', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manager_notes', models.TextField(blank=True, help_text="Manager's notes on approval/rejection")),
                ('approved_at', models.DateTimeField(blank=True, help_text='When manager approved/rejected', null=True)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When admin issued the refund', null=True)),
                ('refund_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider for the refund', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved/rejected the request', limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='authentication.booking')),
                ('issued_by', models.ForeignKey(blank=True, help_text='Admin who issued the refund', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_issued', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Staff or Guest who requested the refund', limit_choices_to={'role__in': ['STAFF', 'GUEST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestComplaintEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_description', models.TextField(help_text="Description of the guest's complaint")),
                ('staff_notes', models.TextField(blank=True, help_text="Staff's notes about the complaint")),
                ('manager_notes', models.TextField(blank=True, help_text="Manager's resolution notes")),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_escalations', to='authentication.booking')),
                ('guest', models.ForeignKey(limit_choices_to={'role': 'GUEST'}, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_escalations', to=settings.AUTH_USER_MODEL)),
                ('reported_by_staff', models.ForeignKey(help_text='Staff member who escalated the complaint', limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_complaints', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(help_text='Manager assigned to handle escalation', limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Complaint Escalation',
                'verbose_name_plural': 'Guest Complaint Escalations',
                'db_table': 'guest_complaint_escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('GUEST', 'Guest'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator')], help_text='Role of the user at time of action', max_length=20)),
                ('action', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_ISSUED', 'Refund Issued'), ('ROOM_CREATED', 'Room Created'), ('ROOM_UPDATED', 'Room Updated'), ('ROOM_DELETED', 'Room Deleted'), ('PRICING_CHANGED', 'Pricing Changed'), ('ROOM_STATUS_CHANGED', 'Room Status Changed'), ('STAFF_REGISTERED', 'Staff Member Registered'), ('STAFF_DEACTIVATED', 'Staff Member Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('COMPLAINT_ESCALATED', 'Guest Complaint Escalated'), ('COMPLAINT_RESOLVED', 'Guest Complaint Resolved'), ('GUEST_PROFILE_VIEWED', 'Guest Profile Viewed'), ('LOGIN_SUCCESSFUL', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed')], help_text='Type of action performed', max_length=50)),
                ('affected_entity_type', models.CharField(help_text='Type of entity affected (Booking, Room, Payment, etc.)', max_length=50)),
                ('affected_entity_id', models.IntegerField(blank=True, help_text='ID of the affected entity', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON object tracking what changed (old values, new values)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(blank=True, help_text='User affected by this action (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_affected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roomhousekeepinglog',
            index=models.Index(fields=['room', '-created_at'], name='room_housek_room_id_e623ec_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['booking', 'status'], name='refund_requ_booking_83a718_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', '-created_at'], name='refund_requ_status_9f855c_idx'),
        ),
        migrations.AddIndex(
            model_name='guestcomplaintescalation',
            index=models.Index(fields=['status', '-created_at'], name='guest_compl_status_b95631_idx'),
        ),
        migrations.AddIndex(
            model_name='guestcomplaintescalation',
            index=models.Index(fields=['escalated_to', 'status'], name='guest_compl_escalat_bbd6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['affected_entity_type', 'affected_entity_id'], name='audit_logs_affecte_660928_idx'),
        ),
    ]
