# Generated by Django 4.2 on 2026-04-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_messagereply'),
        ('authentication', '0008_alter_payment_booking'),
    ]

    operations = [
    ]
