# Generated by Django 4.2 on 2026-04-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_merge_0003_messagereply_0008_alter_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When was guest last notified?', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Has guest been notified of reply?'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='staff_response',
            field=models.TextField(blank=True, help_text="Staff's response message"),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
