# Generated by Django 6.0.2 on 2026-05-01 11:28

import django.db.models.deletion
import secrets
import string
from django.conf import settings
from django.db import migrations, models


def populate_booking_references(apps, schema_editor):
    Booking = apps.get_model('authentication', 'Booking')
    alphabet = string.ascii_uppercase + string.digits

    for booking in Booking.objects.filter(booking_reference__isnull=True):
        reference = f"CEBU-{''.join(secrets.choice(alphabet) for _ in range(6))}"
        while Booking.objects.filter(booking_reference=reference).exists():
            reference = f"CEBU-{''.join(secrets.choice(alphabet) for _ in range(6))}"
        booking.booking_reference = reference
        booking.save(update_fields=['booking_reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_messagereply_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Random guest-facing reference code used during check-in verification', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who completed check-in verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_booking_references, migrations.RunPython.noop),
    ]
