# Generated by Django 6.0.2 on 2026-05-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_booking_booking_reference_booking_contact_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('pending_onsite', 'Pending Onsite'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=20),
        ),
    ]
