# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_add_booking_no_show_checkin_checkout_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('pending_onsite', 'Pending Onsite'),
                    ('CANCELLED', 'Cancelled'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('REFUND_PENDING', 'Refund Pending'),
                    ('REFUNDED', 'Refunded'),
                    ('PARTIALLY_REFUNDED', 'Partially Refunded'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
