# Generated by Django 6.0.2 on 2026-05-11 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_payment_status_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], db_index=True, default='CLEAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomhousekeepinglog',
            name='current_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roomhousekeepinglog',
            name='previous_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], max_length=20),
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('clean', 'Clean'), ('inspect', 'Inspect'), ('maintenance', 'Maintenance')], default='clean', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='authentication.room')),
            ],
            options={
                'verbose_name': 'Housekeeping Task',
                'verbose_name_plural': 'Housekeeping Tasks',
                'db_table': 'housekeeping_tasks',
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['room', 'status'], name='housekeepin_room_id_a30c3c_idx'), models.Index(fields=['assigned_to', 'status'], name='housekeepin_assigne_c83cee_idx')],
            },
        ),
    ]
