# Generated by Django 4.2.30 on 2026-05-11 08:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def backfill_testimonial_review_fields(apps, schema_editor):
    Testimonial = apps.get_model('authentication', 'Testimonial')
    for testimonial in Testimonial.objects.all():
        testimonial.content = testimonial.content or testimonial.comment
        if testimonial.is_approved:
            testimonial.status = 'approved'
        testimonial.save(update_fields=['content', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_activitylog_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_testimonial_review_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_CHECKED_IN', 'Booking Checked In'), ('BOOKING_CHECKED_OUT', 'Booking Checked Out'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUND_REQUESTED_BY_GUEST', 'Refund Requested by Guest'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_REJECTED', 'Refund Rejected'), ('REFUND_ISSUED', 'Refund Issued'), ('ROOM_CREATED', 'Room Created'), ('ROOM_UPDATED', 'Room Updated'), ('ROOM_DELETED', 'Room Deleted'), ('PRICING_CHANGED', 'Pricing Changed'), ('ROOM_STATUS_CHANGED', 'Room Status Changed'), ('STAFF_REGISTERED', 'Staff Member Registered'), ('STAFF_DEACTIVATED', 'Staff Member Deactivated'), ('STAFF_REACTIVATED', 'Staff Member Reactivated'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('COMPLAINT_ESCALATED', 'Guest Complaint Escalated'), ('COMPLAINT_SUBMITTED', 'Guest Complaint Submitted'), ('COMPLAINT_RESOLVED', 'Guest Complaint Resolved'), ('GUEST_PROFILE_VIEWED', 'Guest Profile Viewed'), ('LOGIN_SUCCESSFUL', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('TWO_FACTOR_ENABLED', '2FA Enabled'), ('TWO_FACTOR_DISABLED', '2FA Disabled'), ('TESTIMONIAL_APPROVED', 'Testimonial Approved'), ('TESTIMONIAL_REJECTED', 'Testimonial Rejected')], help_text='Type of action performed', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
