# Generated by Django 4.2.30 on 2026-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_add_testimonial_review_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_policy',
            field=models.CharField(choices=[('FREE', 'Free (100% refund)'), ('STANDARD', 'Standard (48-hour refund policy)'), ('NON_REFUNDABLE', 'Non-Refundable (0% refund)')], default='FREE', help_text='Policy for this booking', max_length=20),
        ),
    ]
