# Generated by Django 6.0.2 on 2026-05-11 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_booking_cancellation_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, help_text='When the refund was issued', null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Manager or admin who issued the refund', limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested by Staff'), ('APPROVED', 'Pending Issue'), ('REJECTED', 'Rejected by Manager'), ('ISSUED', 'Refund Issued')], default='REQUESTED', help_text='Current status of refund request', max_length=20),
        ),
    ]
